pipeline {
  agent any
  environment {
    //DOCKER_IMAGE = "your-docker-username/frontend-app"
    DOCKER_IMAGE = "vuedemo"
    DOCKER_TAG = "latest"
  }
  stages {
    // 阶段1：拉取代码
    stage('Checkout') {
      steps {
        //git branch: 'main', url: 'https://github.com/your-username/frontend-repo.git'
        git branch: 'main', url: 'https://github.com/xuepp/jenkins_demo.git'
      }
    }
    // 阶段2：构建 Docker 镜像
    stage('Build') {
      steps {
        script {
          docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
        }
      }
    }
    // 阶段3：运行容器
    stage('Deploy') {
      steps {
        script {
          // 停止并删除旧容器
          sh 'docker stop vuedemo || true'
          sh 'docker rm vuedemo || true'
          // 启动新容器
          sh "docker run -d --name vuedemo -p 80:80 ${DOCKER_IMAGE}:${DOCKER_TAG}"
        }
      }
    }
  }
}